# Generated by Django 5.2.18 on 2026-10-09 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.PositiveSmallIntegerField(default=0)),
                ('due_date', models.DateField()),
                ('miss_count', models.PositiveIntegerField(default=0)),
                ('last_answered_at', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='quizzes.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'due_date'], name='progress_qu_user_id_a2a13f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='unique_question_state')],
            },
        ),
    ]
