# Generated by Django 5.2.18 on 2026-10-10 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_questionstate'),
        ('quizzes', '0002_quizattempt_quizattemptquestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OlderEventCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='older_event_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OlderEventCheckQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('answer', models.JSONField(blank=True, null=True)),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('older_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='progress.oldereventcheck')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quizzes.question')),
            ],
            options={
                'ordering': ['older_check', 'position'],
            },
        ),
        migrations.AddConstraint(
            model_name='oldereventcheck',
            constraint=models.UniqueConstraint(fields=('user', 'milestone'), name='unique_check_milestone'),
        ),
        migrations.AddConstraint(
            model_name='oldereventcheckquestion',
            constraint=models.UniqueConstraint(fields=('older_check', 'position'), name='unique_check_position'),
        ),
    ]
