# Generated by Django 5.2.18 on 2026-10-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_quiz_and_xp_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='key',
            field=models.CharField(choices=[('finale_percentage', 'finale_percentage'), ('quiz_pass_percentage', 'quiz_pass_percentage'), ('quiz_missed_weight', 'quiz_missed_weight'), ('xp_quiz_first_pass', 'xp_quiz_first_pass'), ('xp_quiz_retake', 'xp_quiz_retake'), ('xp_review_correct', 'xp_review_correct'), ('xp_check_correct', 'xp_check_correct'), ('xp_daily_login', 'xp_daily_login'), ('xp_daily_goal_bonus', 'xp_daily_goal_bonus'), ('daily_goal_xp', 'daily_goal_xp'), ('goal_overflow_percentage', 'goal_overflow_percentage'), ('level_base_xp', 'level_base_xp'), ('level_step_xp', 'level_step_xp')], max_length=64, unique=True),
        ),
    ]
