# Generated by Django 5.2.18 on 2026-10-09 20:04

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('event', 'Event'), ('person', 'Person'), ('place', 'Place'), ('institution', 'Institution'), ('work', 'Work'), ('concept', 'Concept')], max_length=16)),
                ('slug', models.SlugField(help_text='Used in [[slug]] links.', max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('body_md', models.TextField(blank=True, verbose_name='body (Markdown)')),
                ('event_date', models.DateField(blank=True, help_text='New Style (Gregorian). Best guess if not exact.', null=True)),
                ('date_certainty', models.CharField(choices=[('exact', 'Exact'), ('approximate', 'Approximate'), ('estimated', 'Estimated')], default='exact', max_length=16)),
                ('date_note_old_style', models.CharField(blank=True, max_length=200, verbose_name='Old Style date note')),
                ('region', models.CharField(blank=True, max_length=100)),
                ('importance', models.CharField(blank=True, choices=[('major', 'Major'), ('notable', 'Notable'), ('minor', 'Minor')], help_text='Events only.', max_length=16)),
                ('year_order', models.PositiveSmallIntegerField(default=0, help_text='Order among events in the same year.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['event_date', 'year_order', 'title'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['title'], name='entry_title_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.TextField()),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='URL')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='content.entry')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
