# Generated by Django 5.2.18 on 2026-10-09 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='content.entry')),
                ('to_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.entry')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_entry', 'to_entry'), name='unique_relation'), models.CheckConstraint(condition=models.Q(('from_entry', models.F('to_entry')), _negated=True), name='no_self_relation')],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1, help_text='Order in the gallery. Reference in the body as ![[position]].')),
                ('file', models.ImageField(height_field='height', upload_to='entries/', width_field='width')),
                ('width', models.PositiveIntegerField(editable=False, null=True)),
                ('height', models.PositiveIntegerField(editable=False, null=True)),
                ('caption', models.CharField(max_length=300)),
                ('credit', models.CharField(blank=True, max_length=200)),
                ('license_note', models.CharField(help_text="For example: public domain, or the owner's own material.", max_length=200)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.entry')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('entry', 'position'), name='unique_image_position')],
            },
        ),
    ]
