# Generated by Django 5.2.18 on 2026-10-09 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_entryrelation_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['start_date', 'end_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='phase_end_after_start', violation_error_message='The end date must not be before the start date.')],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('regular', 'Regular'), ('opening', 'Opening (other tracks start after it)'), ('finale', 'Finale (unlocks after the threshold in every track)')], default='regular', max_length=16)),
                ('position', models.PositiveSmallIntegerField(help_text='Display order.', unique=True)),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind__in', ['opening', 'finale'])), fields=('kind',), name='one_opening_one_finale_track', violation_error_message='There can be only one opening and one finale track.')],
            },
        ),
        migrations.CreateModel(
            name='GateRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(limit_choices_to={'type': 'event'}, on_delete=django.db.models.deletion.CASCADE, related_name='gate_requirements', to='content.entry')),
                ('required_event', models.ForeignKey(limit_choices_to={'type': 'event'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.entry')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'required_event'), name='unique_gate'), models.CheckConstraint(condition=models.Q(('event', models.F('required_event')), _negated=True), name='no_self_gate', violation_error_message='An event cannot require itself.')],
            },
        ),
        migrations.CreateModel(
            name='TrackEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('entry', models.ForeignKey(limit_choices_to={'type': 'event'}, on_delete=django.db.models.deletion.CASCADE, related_name='track_items', to='content.entry', verbose_name='event')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.track')),
            ],
            options={
                'verbose_name': 'track event',
                'ordering': ['track', 'position'],
                'constraints': [models.UniqueConstraint(fields=('track', 'position'), name='unique_track_position'), models.UniqueConstraint(fields=('track', 'entry'), name='unique_track_entry')],
            },
        ),
    ]
