/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["config_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Csrf */
        get: operations["apps_accounts_api_csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login View */
        post: operations["apps_accounts_api_login_view"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout View */
        post: operations["apps_accounts_api_logout_view"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["apps_accounts_api_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entries */
        get: operations["apps_content_api_list_entries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entry */
        get: operations["apps_content_api_get_entry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries/{slug}/finished-reading": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finished Reading */
        post: operations["apps_content_api_finished_reading"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries/{slug}/quiz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["apps_quizzes_api_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quiz-attempts/{attempt_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit */
        post: operations["apps_quizzes_api_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["apps_gamification_api_dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Time Zone */
            time_zone: string;
            /** Is Admin */
            is_admin: boolean;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Time Zone */
            time_zone?: string | null;
        };
        /**
         * Type
         * @enum {string}
         */
        Type: "event" | "person" | "place" | "institution" | "work" | "concept";
        /** EntrySummaryOut */
        EntrySummaryOut: {
            /**
             * Locked
             * @default false
             * @constant
             */
            locked: false;
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Event Date */
            event_date: string | null;
            /** Date Certainty */
            date_certainty: string;
            /** Region */
            region: string;
            /** Importance */
            importance: string;
            /** Progress */
            progress: string | null;
        };
        /**
         * LockedEntryOut
         * @description Title only, plus the date that the timeline shows for locked events (scope 3.4).
         */
        LockedEntryOut: {
            /**
             * Locked
             * @default true
             * @constant
             */
            locked: true;
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Event Date */
            event_date: string | null;
        };
        /** EntryDetailOut */
        EntryDetailOut: {
            /**
             * Locked
             * @default false
             * @constant
             */
            locked: false;
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Event Date */
            event_date: string | null;
            /** Date Certainty */
            date_certainty: string;
            /** Region */
            region: string;
            /** Importance */
            importance: string;
            /** Progress */
            progress: string | null;
            /** Body Md */
            body_md: string;
            /** Date Note Old Style */
            date_note_old_style: string;
            /** Tracks */
            tracks: string[];
            /** Phases */
            phases: string[];
            /** Images */
            images: components["schemas"]["ImageOut"][];
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
            /** Related */
            related: components["schemas"]["RelatedOut"][];
            /** Links */
            links: {
                [key: string]: components["schemas"]["LinkOut"];
            };
        };
        /** ImageOut */
        ImageOut: {
            /** Position */
            position: number;
            /** Src */
            src: string;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Caption */
            caption: string;
            /** Credit */
            credit: string;
            /** License Note */
            license_note: string;
        };
        /**
         * LinkOut
         * @description A [[slug]] target in the body. Locked targets render as plain titles.
         */
        LinkOut: {
            /** Title */
            title: string;
            /** Locked */
            locked: boolean;
        };
        /** RelatedOut */
        RelatedOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Locked */
            locked: boolean;
        };
        /** SourceOut */
        SourceOut: {
            /** Citation */
            citation: string;
            /** Url */
            url: string;
        };
        /** ProgressOut */
        ProgressOut: {
            /** State */
            state: string;
        };
        /** QuestionOut */
        QuestionOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Prompt */
            prompt: string;
            /** Options */
            options?: string[] | null;
            /** Items */
            items?: string[] | null;
        };
        /** QuizOut */
        QuizOut: {
            /** Attempt Id */
            attempt_id: number;
            /** Questions */
            questions: components["schemas"]["QuestionOut"][];
        };
        /** QuestionResultOut */
        QuestionResultOut: {
            /** Question Id */
            question_id: number;
            /** Correct */
            correct: boolean;
            /** Your Answer */
            your_answer: number | boolean | string[] | string;
            /** Correct Answer */
            correct_answer: number | boolean | string[] | string;
            /** Explanation */
            explanation: string;
        };
        /** QuizFailedOut */
        QuizFailedOut: {
            /**
             * Passed
             * @default false
             * @constant
             */
            passed: false;
            /** Score */
            score: number;
            /** Total */
            total: number;
        };
        /** QuizPassedOut */
        QuizPassedOut: {
            /**
             * Passed
             * @default true
             * @constant
             */
            passed: true;
            /** Score */
            score: number;
            /** Total */
            total: number;
            /** Xp Awarded */
            xp_awarded: number;
            /** Results */
            results: components["schemas"]["QuestionResultOut"][];
        };
        /** AnswerIn */
        AnswerIn: {
            /** Question Id */
            question_id: number;
            /** Answer */
            answer: number | boolean | string[] | string;
        };
        /** SubmitIn */
        SubmitIn: {
            /** Answers */
            answers: components["schemas"]["AnswerIn"][];
        };
        /** DashboardOut */
        DashboardOut: {
            goal: components["schemas"]["GoalOut"];
            streak: components["schemas"]["StreakOut"];
            level: components["schemas"]["LevelOut"];
            /** Reviews Due */
            reviews_due: number;
        };
        /** GoalOut */
        GoalOut: {
            /** Target */
            target: number;
            /** Earned Today */
            earned_today: number;
            /** Reached */
            reached: boolean;
        };
        /** LevelOut */
        LevelOut: {
            /** Level */
            level: number;
            /** Title */
            title: string;
            /** Total Xp */
            total_xp: number;
            /** Xp Into Level */
            xp_into_level: number;
            /** Xp For Next Level */
            xp_for_next_level: number;
        };
        /** StreakOut */
        StreakOut: {
            /** Current */
            current: number;
            /** Longest */
            longest: number;
            /** Freezes Held */
            freezes_held: number;
            /** Max Freezes */
            max_freezes: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    config_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    apps_accounts_api_csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_accounts_api_login_view: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    apps_accounts_api_logout_view: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_accounts_api_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    apps_content_api_list_entries: {
        parameters: {
            query?: {
                type?: components["schemas"]["Type"] | null;
                track?: number | null;
                phase?: number | null;
                region?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["EntrySummaryOut"] | components["schemas"]["LockedEntryOut"])[];
                };
            };
        };
    };
    apps_content_api_get_entry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryDetailOut"] | components["schemas"]["LockedEntryOut"];
                };
            };
        };
    };
    apps_content_api_finished_reading: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressOut"];
                };
            };
        };
    };
    apps_quizzes_api_start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizOut"];
                };
            };
        };
    };
    apps_quizzes_api_submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizPassedOut"] | components["schemas"]["QuizFailedOut"];
                };
            };
        };
    };
    apps_gamification_api_dashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
        };
    };
}
