# Generated by Django 5.2.18 on 2026-10-09 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True False'), ('date_ordering', 'Date Ordering'), ('fill_blank', 'Fill in the blank')], max_length=20)),
                ('prompt', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.entry')),
            ],
            options={
                'ordering': ['entry', 'id'],
            },
        ),
    ]
