# Generated by Django 5.2.18 on 2026-10-09 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_seed_phases_tracks'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='content.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('answer', models.JSONField(blank=True, null=True)),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quizzes.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quizzes.question')),
            ],
            options={
                'ordering': ['attempt', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'entry'], name='quizzes_qui_user_id_e2d6dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizattemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'position'), name='unique_attempt_position'),
        ),
        migrations.AddConstraint(
            model_name='quizattemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question'),
        ),
    ]
