# Generated by Django 5.2.18 on 2026-10-09 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XpEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('quiz_first_pass', 'Quiz First Pass'), ('quiz_retake', 'Quiz Retake'), ('review', 'Review'), ('practice', 'Practice'), ('older_event_check', 'Older Event Check'), ('daily_challenge', 'Daily Challenge'), ('daily_login', 'Daily Login'), ('daily_goal_bonus', 'Daily Goal Bonus')], max_length=32)),
                ('amount', models.PositiveIntegerField()),
                ('local_date', models.DateField(help_text="The user's local date when the XP was earned.")),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'local_date'], name='gamificatio_user_id_658cb7_idx')],
            },
        ),
    ]
